name: CI - Unit - Pulsar Manager
on:
  pull_request:
    branches:
      - master

jobs:

  unit-tests:
    name:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: checkout
        uses: actions/checkout@v1

      - name: run unit tests for pulsar manager
        run: ./gradlew build 
